### ISSUE TITLE
RxStarscream is not building with carthage

### ISSUE THREAD

**Issue by JeanAzzopardi** [GuyKahlon/RxStarscream#11]
Getting this error when installing with carthage.

```
ld: '/xxx/Carthage/Checkouts/RxStarscream/Carthage/Build/iOS/RxTest.framework/RxTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

I've submitted a P.R. to fix this issue: https://github.com/RxSwiftCommunity/RxStarscream/pull/10

**Comment by nmazzon** [comment]
Any news? Fix is merged, I have to set "master" dependency on cartfile to use it, but I don't like this . You can commit new files and I don't see modifications..

**Comment by freak4pc** [comment]
@nmazzon Sorry for the delayed reply here. Unfortunately I'm not a Carthage aficionado. Can you describe what's the trouble with it at the moment? Would serving a pre-built binary help?

**Comment by nmazzon** [comment]
Sorry but now I moved all project to Cocoa pod, so now I can not give you what you need. For me you can close this bug.
