### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by fassko** [GuyKahlon/RxStarscream#21]
- [ ] Swift 4.2 and Xcode 10
- [ ] newest RxSwift and Starscream
- [ ] readme info about older Swift versions

**Comment by pedrommcarrasco** [comment]
Can help if needed 😄

**Comment by fassko** [comment]
@pedrommcarrasco Let's wait for new release from Starscream. I hope I can do it in quite soon.

**Comment by freak4pc** [comment]
Taking care of this right now :]
