### ISSUE TITLE
Use WebsocketClient protocol to support mocking

### ISSUE THREAD

**Issue by fb55** [GuyKahlon/RxStarscream#22]
This was introduced in https://github.com/daltoniam/Starscream/pull/311. Afaict there should be nothing that prevents RxStarscream to replace the dependence on `Websocket` classes with the protocol, which would make it much easier to write tests.

**Comment by freak4pc** [comment]
Sounds good! Will gladly accept and review a PR for this. 
Thanks! :)

**Comment by fb55** [comment]
There we go: #23
