### ISSUE TITLE
Socket.io connection

### ISSUE THREAD

**Issue by OmeraWasTaken** [GuyKahlon/RxStarscream#28]
Hello 👋,
I wondering is it possible to use RxStarscream with a serveur on Socket.io ? I know I should use Socket.io swift client but have you already try to make it work without the socket.io swift client ? I manage to connect but I get instant disconnect with code error 1000 but according to the RFC 6455 1000 is like a normal closure. If you have any idea or help to provide I will really appreciate it 😄 !

**Comment by freak4pc** [comment]
Hey @OmeraWasTaken - 
RxStarscream is simply a wrapper around [Starscream](https://github.com/daltoniam/starscream) - you might want to point your question there :)
