### ISSUE TITLE
issue with the real License.

### ISSUE THREAD

**Issue by michaelhenry** [GuyKahlon/RxStarscream#33]
In [README](https://github.com/RxSwiftCommunity/RxStarscream/blob/master/README.md) it's under `MIT`
but in [LICENSE](https://github.com/RxSwiftCommunity/RxStarscream/blob/master/LICENSE) file, it's under ` Apache License`

**Comment by freak4pc** [comment]
Yikes. This should be MIT. I'll update.

**Comment by michaelhenry** [comment]
@freak4pc Thanks 👍

**Comment by freak4pc** [comment]
Fixed in 295d44f. Note though that Starscream itself is Apache, so you conform to that as well.

**Comment by michaelhenry** [comment]
Yes, that's right.
