### ISSUE TITLE
support for RxSwift 3.x version?

### ISSUE THREAD

**Issue by highlystuff** [GuyKahlon/RxStarscream#9]
Now,My project use RxSwift 3.5.0 version, which can not be compatible with the version that RxStarscream depends on(~>2.5.0)

**Comment by freak4pc** [comment]
RxStarscream actually depends on `~> 3` 
Can you confirm on your end you have the latest version? @highlystuff

**Comment by highlystuff** [comment]
When I pod install,it told me the latest cocoapods version was 0.2, why not push the 0.6 version pod spec to the spec repo?

**Comment by freak4pc** [comment]
That's a very good question. I don't have the privileges to push a version up, unfortunately. Only @GuyKahlon has. I also pinged him via e-mail so hope this would be sorted out quickly!

**Comment by freak4pc** [comment]
All good here ! 0.7 was just pushed and you should have no issues updating. Let me know if anything wrong :)

**Comment by highlystuff** [comment]
@freak4pc Brilliant! No problem now, so now you're the master? I cannot wait to employ it in my project.

**Comment by freak4pc** [comment]
Hey @highlystuff, not the master of it :) I've been a member of the project for a while but the original owner was kind enough to provide Cocoapods credentials so I'll be able to push new versions as they become available.
